### ISSUE TITLE
proxy 跨域问题

### ISSUE THREAD

**Issue by gogov5** [byteblogs168/hello-blog-admin#3]
本地部署， 后台java已经启动，运行管理前端，管理页面可当路， 当点击“分析页面”时，出现以下代理错误， 是不是哪里缺少设置？ 
 
 App running at:
  - Local:   http://localhost:8000/admin/
  - Network: http://192.168.0.21:8000/admin/

Proxy error: Could not proxy request //monitor/system/v1/get from localhost:8000 to http://127.0.0.1:8086/api/hello-blog-service.

**Comment by byteblogs168** [comment]
这个你检查一下vue.config.js文件的devServer的代理配置是不是配置有误。

**Comment by gogov5** [comment]
> 这个你检查一下vue.config.js文件的devServer的代理配置是不是配置有误。

感谢， 加了端口：8086就ok了，
