### ISSUE TITLE
文章图片无法保存

### ISSUE THREAD

**Issue by gogov5** [byteblogs168/hello-blog-admin#4]
您好，
采用本地部署方式， 服务器OSS 已设置为如下
local path ：/Users/bdguo/my-blog-project/upload/
域名：http://127.0.0.1:8086/api/hello-blog-service/

在后台添加文章后， 插入图片和头图， 保存。 再次点编辑， 图片都没有了， load 不出来， 这是什么问题呢？ 谢谢

**Comment by byteblogs168** [comment]
原因是因为  registry.addResourceHandler("/files/**").addResourceLocations("file:///" + defaultPath);这里默认了前缀files,所以http://127.0.0.1:8086/api/hello-blog-service/files/a.png。这个前缀已经删除。谢谢您的反馈。
